version: '3.9'
services:
  # web:
  #   build: .
  #   ports:
  #     - 80:8080
  #   depends_on:
  #     - 'mongo'
  #     - 'redis'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - 27017:27017
    restart: always
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - 6379:6379
    restart: always