version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Tokyo